"""Add is_pinned pinned_by edited_at to comments

Revision ID: 00018e4ea081
Revises: 1aed0ffd5609
Create Date: 2026-07-30 00:17:44.411249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00018e4ea081'
down_revision: Union[str, Sequence[str], None] = '1aed0ffd5609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('comments', sa.Column('pinned_by', sa.String(length=150), nullable=True))
    op.add_column('comments', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'edited_at')
    op.drop_column('comments', 'pinned_by')
    op.drop_column('comments', 'is_pinned')
    # ### end Alembic commands ###
