"""Add media_urls to flood_reports

Revision ID: 130fc653b690
Revises: fd5bebf6e398
Create Date: 2026-08-18 12:23:36.668614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '130fc653b690'
down_revision: Union[str, Sequence[str], None] = 'fd5bebf6e398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        "UPDATE flood_reports SET media_urls = jsonb_build_array(image_url) WHERE image_url IS NOT NULL AND image_url != ''"
    )
    op.drop_column('flood_reports', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.execute(
        "UPDATE flood_reports SET image_url = media_urls->>0 WHERE media_urls IS NOT NULL AND jsonb_array_length(media_urls) > 0"
    )
    op.drop_column('flood_reports', 'media_urls')
    # ### end Alembic commands ###
