"""add is_bidirectional

Revision ID: 3290af676337
Revises: a757f395bad1
Create Date: 2026-09-02 00:01:24.187916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3290af676337'
down_revision: Union[str, Sequence[str], None] = 'a757f395bad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('is_bidirectional', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_reports', 'is_bidirectional')
    # ### end Alembic commands ###
