"""add_media_urls_to_avoidance_zones

Revision ID: 33ec62de236d
Revises: 8a6a4336a396
Create Date: 2026-09-09 16:25:55.048760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ec62de236d'
down_revision: Union[str, Sequence[str], None] = '8a6a4336a396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_avoidance_zones', sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_avoidance_zones', 'media_urls')
    # ### end Alembic commands ###
