"""Add override columns to FloodAvoidanceZone

Revision ID: 4b0eab81ef37
Revises: 130fc653b690
Create Date: 2026-08-23 23:41:10.339442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0eab81ef37'
down_revision: Union[str, Sequence[str], None] = '130fc653b690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_avoidance_zones', sa.Column('severity_override', sa.Enum('low', 'medium', 'high', 'extreme', name='reportseverity', native_enum=False, length=50), nullable=True))
    op.add_column('flood_avoidance_zones', sa.Column('depth_override', sa.String(length=50), nullable=True))
    op.add_column('flood_avoidance_zones', sa.Column('admin_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_avoidance_zones', 'admin_notes')
    op.drop_column('flood_avoidance_zones', 'depth_override')
    op.drop_column('flood_avoidance_zones', 'severity_override')
    # ### end Alembic commands ###
