"""Add lat lng to community_posts

Revision ID: 84c00c5d976b
Revises: a78b8505a56c
Create Date: 2026-09-07 00:14:47.635792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c00c5d976b'
down_revision: Union[str, Sequence[str], None] = 'a78b8505a56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('community_posts', sa.Column('location_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_posts', 'location_lng')
    op.drop_column('community_posts', 'location_lat')
    # ### end Alembic commands ###
