"""add_merge_overrides_to_avoidance_zones

Revision ID: 8a6a4336a396
Revises: a66a677fa71a
Create Date: 2026-09-09 12:46:39.651494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6a4336a396'
down_revision: Union[str, Sequence[str], None] = 'a66a677fa71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_avoidance_zones', sa.Column('passable_vehicles_override', sa.String(length=500), nullable=True))
    op.add_column('flood_avoidance_zones', sa.Column('hidden_hazards_override', sa.String(length=255), nullable=True))
    op.add_column('flood_avoidance_zones', sa.Column('merge_rationale', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_avoidance_zones', 'merge_rationale')
    op.drop_column('flood_avoidance_zones', 'hidden_hazards_override')
    op.drop_column('flood_avoidance_zones', 'passable_vehicles_override')
    # ### end Alembic commands ###
