"""Add comment nested replies and votes

Revision ID: 8dc57b083e5b
Revises: d34f2a2e5eae
Create Date: 2026-07-29 21:38:17.549248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '8dc57b083e5b'
down_revision: Union[str, Sequence[str], None] = 'd34f2a2e5eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', ENUM('UPVOTE', 'DOWNVOTE', name='interactiontype_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_interactions_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comment_interactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_interactions'))
    )
    op.create_index(op.f('ix_comment_interactions_comment_id'), 'comment_interactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_interactions_id'), 'comment_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_comment_interactions_user_id'), 'comment_interactions', ['user_id'], unique=False)
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('upvotes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('comments', sa.Column('downvotes', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_foreign_key(op.f('fk_comments_parent_id_comments'), 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_comments_parent_id_comments'), 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_column('comments', 'downvotes')
    op.drop_column('comments', 'upvotes')
    op.drop_column('comments', 'parent_id')
    op.drop_index(op.f('ix_comment_interactions_user_id'), table_name='comment_interactions')
    op.drop_index(op.f('ix_comment_interactions_id'), table_name='comment_interactions')
    op.drop_index(op.f('ix_comment_interactions_comment_id'), table_name='comment_interactions')
    op.drop_table('comment_interactions')
    # ### end Alembic commands ###
