"""add_city_to_flood_reports

Revision ID: a66a677fa71a
Revises: 84c00c5d976b
Create Date: 2026-09-07 14:57:55.937934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66a677fa71a'
down_revision: Union[str, Sequence[str], None] = '84c00c5d976b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('city', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_flood_reports_city'), 'flood_reports', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flood_reports_city'), table_name='flood_reports')
    op.drop_column('flood_reports', 'city')
    # ### end Alembic commands ###
