"""Add name column to flood_avoidance_zones

Revision ID: a757f395bad1
Revises: 4b0eab81ef37
Create Date: 2026-08-30 22:47:35.108735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a757f395bad1'
down_revision: Union[str, Sequence[str], None] = '4b0eab81ef37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_avoidance_zones', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_avoidance_zones', 'name')
    # ### end Alembic commands ###
