"""replace is_pinned with pin_order

Revision ID: a78b8505a56c
Revises: cb43b8f52e55
Create Date: 2026-09-06 22:51:39.031517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78b8505a56c'
down_revision: Union[str, Sequence[str], None] = 'cb43b8f52e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_places', sa.Column('pin_order', sa.Integer(), nullable=True))
    op.drop_column('saved_places', 'is_pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_places', sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('saved_places', 'pin_order')
    # ### end Alembic commands ###
