"""Add is_pinned to saved_places

Revision ID: cb43b8f52e55
Revises: 3290af676337
Create Date: 2026-09-06 22:26:34.361711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb43b8f52e55'
down_revision: Union[str, Sequence[str], None] = '3290af676337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_places', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_places', 'is_pinned')
    # ### end Alembic commands ###
