"""add display_full_name to profile

Revision ID: d09badc74a1d
Revises: f6ff95c1ee3e
Create Date: 2026-08-09 21:20:11.576812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09badc74a1d'
down_revision: Union[str, Sequence[str], None] = 'f6ff95c1ee3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('display_full_name', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'display_full_name')
    # ### end Alembic commands ###
