"""Add profile ui and metrics columns

Revision ID: f6ff95c1ee3e
Revises: 00018e4ea081
Create Date: 2026-08-07 21:43:41.027024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ff95c1ee3e'
down_revision: Union[str, Sequence[str], None] = '00018e4ea081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('cover_color', sa.String(length=20), server_default='#3B82F6', nullable=False))
    op.add_column('profiles', sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('profiles', sa.Column('trust_score', sa.Integer(), server_default='50', nullable=False))
    op.add_column('profiles', sa.Column('reports_submitted', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('reports_approved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('reports_rejected', sa.Integer(), server_default='0', nullable=False))
    op.add_column('profiles', sa.Column('accuracy_rate', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'accuracy_rate')
    op.drop_column('profiles', 'reports_rejected')
    op.drop_column('profiles', 'reports_approved')
    op.drop_column('profiles', 'reports_submitted')
    op.drop_column('profiles', 'trust_score')
    op.drop_column('profiles', 'is_public')
    op.drop_column('profiles', 'cover_color')
    op.alter_column('comments', 'content',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
