"""phase2_spatial_dedup_1_to_n

Revision ID: fd5bebf6e398
Revises: 3276b301538f
Create Date: 2026-08-16 23:56:58.356545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5bebf6e398'
down_revision: Union[str, Sequence[str], None] = '3276b301538f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_avoidance_zones', sa.Column('curated_by_admin_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_flood_avoidance_zones_report_id'), table_name='flood_avoidance_zones')
    op.create_index(op.f('ix_flood_avoidance_zones_curated_by_admin_id'), 'flood_avoidance_zones', ['curated_by_admin_id'], unique=False)
    op.drop_constraint(op.f('fk_flood_avoidance_zones_report_id_flood_reports'), 'flood_avoidance_zones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_flood_avoidance_zones_curated_by_admin_id_users'), 'flood_avoidance_zones', 'users', ['curated_by_admin_id'], ['id'], ondelete='SET NULL')
    op.drop_column('flood_avoidance_zones', 'report_id')
    op.add_column('flood_reports', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_flood_reports_zone_id'), 'flood_reports', ['zone_id'], unique=False)
    op.create_foreign_key(op.f('fk_flood_reports_zone_id_flood_avoidance_zones'), 'flood_reports', 'flood_avoidance_zones', ['zone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_flood_reports_zone_id_flood_avoidance_zones'), 'flood_reports', type_='foreignkey')
    op.drop_index(op.f('ix_flood_reports_zone_id'), table_name='flood_reports')
    op.drop_column('flood_reports', 'zone_id')
    op.add_column('flood_avoidance_zones', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_flood_avoidance_zones_curated_by_admin_id_users'), 'flood_avoidance_zones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_flood_avoidance_zones_report_id_flood_reports'), 'flood_avoidance_zones', 'flood_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_flood_avoidance_zones_curated_by_admin_id'), table_name='flood_avoidance_zones')
    op.create_index(op.f('ix_flood_avoidance_zones_report_id'), 'flood_avoidance_zones', ['report_id'], unique=False)
    op.drop_column('flood_avoidance_zones', 'curated_by_admin_id')
    # ### end Alembic commands ###
