"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Eye, Filter, Map as MapIcon, Search, TableProperties } from "lucide-react";
import { Button, Card, CardContent, DatePicker, Input, Select, Tabs } from "@/shared/ui";
import { FloodEventDetailModal } from "./FloodEventDetailModal";
import { HistoricalEventsMap } from "./HistoricalEventsMap";
import { getFloodEventHistory, type FloodEventRecord, type FloodHistoryFilters } from "./floodHistoryApi";

const initialFilters: FloodHistoryFilters = { status: "all", severity: "", dateFrom: "", dateTo: "", barangay: "", road: "", search: "" };
const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—";
const places = (event: FloodEventRecord) => event.locations.map((location) => location.display_name).join(" · ") || "Location not recorded";

export function FloodEventRecords() {
  const [filters, setFilters] = useState(initialFilters);
  const [selectedEventId, setSelectedEventId] = useState<number | null>(null);
  const [detailEventId, setDetailEventId] = useState<number | null>(null);
  const [mobileView, setMobileView] = useState<"map" | "list">("list");
  const { data: events = [], isLoading, isError } = useQuery({ queryKey: ["flood-event-history", filters], queryFn: () => getFloodEventHistory(filters) });
  const visibleEvents = useMemo(() => events.filter((event) => !filters.search.startsWith("@multiple") || event.locations.filter((location) => location.location_type !== "city").length > 1), [events, filters.search]);
  const changeFilter = <K extends keyof FloodHistoryFilters>(key: K, value: FloodHistoryFilters[K]) => setFilters((current) => ({ ...current, [key]: value }));
  const selectEvent = (eventId: number) => { setSelectedEventId(eventId); setMobileView("list"); };

  return <section className="space-y-4">
    <Card className="shadow-sm"><CardContent className="space-y-4 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-bold uppercase tracking-wider text-slate-900">Flood Event Records</h2><p className="mt-1 text-xs text-slate-500">Distinct verified incidents; supporting reports remain separate evidence.</p></div><Button variant="ghost" size="sm" onClick={() => setFilters(initialFilters)}><Filter className="mr-1 h-4 w-4" />Clear filters</Button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><Input aria-label="Search events" containerClassName="xl:col-span-2" leftIcon={<Search className="h-4 w-4" />} value={filters.search.startsWith("@multiple") ? "" : filters.search} onChange={(event) => changeFilter("search", event.target.value)} placeholder="Search place" /><Select ariaLabel="Event status" options={[{ value: "all", label: "All statuses" }, { value: "active", label: "Active" }, { value: "ended", label: "Ended" }]} value={filters.status} onChange={(event) => changeFilter("status", event.target.value as FloodHistoryFilters["status"])} /><Select ariaLabel="Peak severity" options={[{ value: "", label: "All severity" }, { value: "low", label: "Low" }, { value: "medium", label: "Medium" }, { value: "high", label: "High" }, { value: "extreme", label: "Extreme" }]} value={filters.severity} onChange={(event) => changeFilter("severity", event.target.value as FloodHistoryFilters["severity"])} /><Input aria-label="Barangay" value={filters.barangay} onChange={(event) => changeFilter("barangay", event.target.value)} placeholder="Barangay" /><Input aria-label="Road or street" value={filters.road} onChange={(event) => changeFilter("road", event.target.value)} placeholder="Road / street" /><Select ariaLabel="Location recurrence" options={[{ value: "all", label: "All locations" }, { value: "multiple", label: "Multiple places" }]} value={filters.search.startsWith("@multiple") ? "multiple" : "all"} onChange={(event) => changeFilter("search", event.target.value === "multiple" ? "@multiple" : "")} /><DatePicker emptyDisplay="From date" ariaLabel="Event date from" value={filters.dateFrom} onChange={(event) => changeFilter("dateFrom", event.target.value)} /><DatePicker emptyDisplay="To date" ariaLabel="Event date to" value={filters.dateTo} onChange={(event) => changeFilter("dateTo", event.target.value)} align="right" /></div></CardContent></Card>
    <Tabs tabs={[{ id: "list", label: "List", icon: TableProperties }, { id: "map", label: "Map", icon: MapIcon }]} activeTab={mobileView} onChange={setMobileView} variant="pills" layoutId="flood-history-mobile-view" fullWidth className="lg:hidden" />
    {isError ? <Card className="border-red-200 bg-red-50 shadow-sm"><CardContent className="p-4 text-sm text-red-800">Flood Event records could not be loaded. Adjust filters or try again.</CardContent></Card> : <div className="grid gap-4 lg:grid-cols-[minmax(0,1.35fr)_minmax(22rem,0.8fr)]"><div className={mobileView === "list" ? "hidden lg:block" : "block"}><HistoricalEventsMap events={visibleEvents} selectedEventId={selectedEventId} onSelectEvent={selectEvent} /></div><div className={mobileView === "map" ? "hidden lg:block" : "block"}><Card className="shadow-sm"><div className="max-h-[38rem] overflow-y-auto">{isLoading ? <p className="p-10 text-center text-sm text-slate-500">Loading records…</p> : visibleEvents.length === 0 ? <p className="p-10 text-center text-sm text-slate-500">No verified Flood Events match these filters.</p> : visibleEvents.map((event) => <article key={event.id} className={`border-b border-slate-100 p-4 last:border-0 ${event.id === selectedEventId ? "bg-blue-50/70" : "hover:bg-slate-50"}`}><button onClick={() => selectEvent(event.id)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">Flood Event #{event.id}</p><p className="mt-1 text-sm text-slate-600">{places(event)}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium capitalize text-slate-700">{event.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>Verified {formatDate(event.verified_at)}</span><span className="text-right capitalize">Peak {event.peak_severity}</span><span>{event.supporting_report_count ?? 0} supporting reports</span><span className="text-right">{event.zones.length} source zones</span></div></button><Button size="sm" variant="ghost" className="mt-3" onClick={() => setDetailEventId(event.id)}><Eye className="mr-1 h-4 w-4" />View event</Button></article>)}</div></Card></div></div>}
    <FloodEventDetailModal eventId={detailEventId} onClose={() => setDetailEventId(null)} />
  </section>;
}
